# ===============================
# Application Name
# ===============================
spring.application.name=FileStroing

# ===============================
# Production Database Configuration - Railway MySQL
# ===============================
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=dMWYxBPNyEbjysFhgqYZYVifUbQEYELt
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# Hibernate / JPA Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# File Upload Configuration
# ===============================
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:uploads/
